# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from husimlite import Ui_HUSimWindow

class Ui_MainLoginWindow(object):
    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(413, 302)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 40, 321, 241))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.UserName = QtWidgets.QLineEdit(self.groupBox)
        self.UserName.setGeometry(QtCore.QRect(100, 70, 181, 20))
        self.UserName.setObjectName("UserName")
        self.Password = QtWidgets.QLineEdit(self.groupBox)
        self.Password.setGeometry(QtCore.QRect(100, 110, 181, 20))
        self.Password.setObjectName("Password")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LoginButton = QtWidgets.QPushButton(self.groupBox)
        self.LoginButton.setGeometry(QtCore.QRect(90, 160, 201, 41))
       
        self.LoginButton.setObjectName("LoginButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.LoginButton.clicked.connect(self.LoginClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HU Simulator Lite"))
        self.groupBox.setTitle(_translate("MainWindow", "SignIn"))
        self.label.setText(_translate("MainWindow", "UserName"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.LoginButton.setText(_translate("MainWindow", "LOGIN"))

   
        
    def LoginClicked(self):
        UN = self.UserName.text()
        Pass = self.Password.text()

        if UN == 'admin' and Pass == 'admin':
            self.groupBox.setTitle("Success")
            
            self.window = QtWidgets.QMainWindow()
            self.HU_ui = Ui_HUSimWindow()
            self.HU_ui.setupUi(self.window)

            self.window.show()
            MainWindow.hide()
            
        else:
            self.groupBox.setTitle("Username or Password is wrong")
      

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainLoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
